### PR TITLE
Update design.v

### PR DESCRIPTION
**Pull request by AaronSMathew**
second adder initialization half_adder 1 to half_adder 2 commit change

### CODE REVIEW

**Comment by adhilsalim** [comment]
@AaronSMathew why did you close the pull?

**Comment by AaronSMathew** [comment]
oh sorry da i thought i already committed it .

**Comment by AaronSMathew** [comment]
oh sorry da i thought i already committed it .

**Comment by adhilsalim** [comment]
bruh are you for serious, your pull is not merged, stop closing it.

**Pull request merged**
